# Numpy 

NumPy is a Python library used for working with arrays.

Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
Arrays are very frequently used in data science, where speed and resources are very important.

NumPy is much faster than Python lists for numerical computations because it is designed specifically for efficient array operations. The main reasons are:

### 1. Contiguous Memory Layout

A Python list stores **references (pointers)** to Python objects, not the actual values.

```python
lst = [1, 2, 3, 4]
```

Memory looks like:

```
List
+-----+-----+-----+-----+
|  *  |  *  |  *  |  *  |
+-----+-----+-----+-----+
   |      |      |      |
   v      v      v      v
  PyInt  PyInt  PyInt  PyInt
```

Each integer is a separate Python object with additional metadata.

A NumPy array stores the values directly in one continuous block of memory.

```python
import numpy as np

arr = np.array([1, 2, 3, 4])
```

Memory looks like:

```
+---+---+---+---+
| 1 | 2 | 3 | 4 |
+---+---+---+---+
```

This improves cache efficiency and reduces memory access time.

---

### 2. Fixed Data Type

Python lists can store mixed data types.

```python
lst = [1, "hello", 3.14, True]
```

NumPy arrays contain elements of a single data type.

```python
arr = np.array([1, 2, 3, 4], dtype=np.int32)
```

Because every element has the same size, NumPy can calculate memory locations directly instead of checking each object's type.

---



In [1]:
# NumPy Creating Arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [2]:
arr

array([1, 2, 3, 4, 5])

In [3]:
print(np.__version__)

2.4.3


In [4]:
type(arr)

numpy.ndarray

## 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [5]:
arr1 = np.array(23)
arr1

array(23)

In [6]:
print(arr1)

23


## 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [7]:
arr   = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [8]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
# Nu?mPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
arr1.ndim

0

In [10]:
arr.ndim

1

In [11]:
arr2.ndim

2

In [12]:
# When the array is created, you can define the number of dimensions by using the ndmin argument.
arr3 = np.array([1,2,3,4,5], ndmin=3)
print(arr3)

[[[1 2 3 4 5]]]


## NumPy Array Indexing

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [13]:
arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [14]:
print(arr[0]+arr[-1])

6


## Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.



In [15]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[0,2])

3


In [16]:
# Access the element on the 2nd row, 5th column:
print(arr[1,4])

10


In [17]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
arr = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ], 
    [
        [7, 8, 9], 
        [10, 11, 12]
    ]
        ])
print(arr[1,0,1])

8


In [19]:
# Negative Indexing
print(arr[-1,-2,-2])

8


## NumPy Array Slicing

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [20]:
# Slice elements from index 1 to index 5 from the following array:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:6])

[2 3 4 5 6]


In [21]:
# Slice elements from index 4 to the end of the array:
print(arr[4:])

[5 6 7 8]


In [22]:
# Slice from the index 3 from the end to index 1 from the end:
print(arr[-3:-1])

[6 7]


In [23]:
# usage of step 
print(arr[::2])

[1 3 5 7]


In [24]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array(
    [
        [1, 2, 3, 4, 5], 
        [6, 7, 8, 9, 10]
    ])

print(arr[:,1:4])


[[2 3 4]
 [7 8 9]]


## NumPy Data Types
| NumPy dtype  | Description      | Typical values               |     Size |
| ------------ | ---------------- | ---------------------------- | -------: |
| `int8`       | Signed integer   | `-128 → 127`                 |   1 byte |
| `int16`      | Signed integer   | `-32,768 → 32,767`           |  2 bytes |
| `int32`      | Signed integer   | ~`-2.1B → 2.1B`              |  4 bytes |
| `int64`      | Signed integer   | Very large integers          |  8 bytes |
| `uint8`      | Unsigned integer | `0 → 255`                    |   1 byte |
| `uint16`     | Unsigned integer | `0 → 65,535`                 |  2 bytes |
| `uint32`     | Unsigned integer | `0 → ~4.3B`                  |  4 bytes |
| `uint64`     | Unsigned integer | Very large positive integers |  8 bytes |
| `float16`    | Floating point   | Decimal numbers              |  2 bytes |
| `float32`    | Floating point   | Decimal numbers              |  4 bytes |
| `float64`    | Floating point   | Decimal numbers              |  8 bytes |
| `complex64`  | Complex number   | `3 + 4j`                     |  8 bytes |
| `complex128` | Complex number   | `3 + 4j`                     | 16 bytes |
| `bool`       | Boolean          | `True / False`               |   1 byte |
| `str_`       | Unicode string   | `"hello"`                    | Variable |
| `bytes_`     | Byte string      | `b"hello"`                   | Variable |
| `object_`    | Python objects   | Lists, custom objects, etc.  | Variable |


In [25]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([1.1,2.0,2.3,4.5])
arr3 = np.array(["apple","banana","mango"])

print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
float64
<U6


In [26]:
arr = arr.astype(np.float32)
print(arr,arr.dtype)

[1. 2. 3. 4. 5.] float32


## NumPy Array Copy vs View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [27]:
arr1 = np.array([1,2,3,4,5])
x = arr.copy()
x[0]=90

print(arr1)
print(x)

[1 2 3 4 5]
[90.  2.  3.  4.  5.]


In [28]:
arr2 = np.array([1,2,3,4,5])
x = arr2.view()

x[0]=90
print(arr2)
print(x)

[90  2  3  4  5]
[90  2  3  4  5]


### Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [29]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


## NumPy Array Shape

The shape of an array is the number of elements in each dimension.
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [30]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)  # ( row, column)

(2, 4)


In [31]:
arr = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ], 
    [
        [7, 8, 9], 
        [10, 11, 12]
    ]
        ])

print(arr.shape) # (2,(2,3))

(2, 2, 3)


## NumPy Array Reshaping

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

### Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [32]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


# NumPy Array Iterating

Iterating means going through elements one by one.
As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
If we iterate on a 1-D array it will go through each element one by one.

In [35]:
arr = np.array([1,2,3,4,5])

for x in arr:
    print(x)

1
2
3
4
5


In [38]:
arr = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

for (x,y,z) in  arr:
    print(y)

2
5


In [39]:
arr.shape

(2, 3)

In [40]:
arr.size

6

In [41]:
arr.itemsize

8

In [42]:
#Boolean Indexing 
arr = np.array([1,2,3,4,5])
arr > 3

array([False, False, False,  True,  True])

In [43]:
arr = np.array( 
    [
        [1,2,3],
        [4,5,6]
    ]
)

arr>2

array([[False, False,  True],
       [ True,  True,  True]])

In [ ]:
# Filter 
arr = np.array(
    [
    [1,2,3],
    [4,5,6]
    ]
)

arr[arr>2]

# It matches the element satisfy the condition if satisfy the accept it and show in the 1D array else

array([3, 4, 5, 6])

In [48]:
# Zeroes : 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [52]:
np.ones(4)

array([1., 1., 1., 1.])

In [53]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
# The np.full() function in NumPy creates a new array of a specified shape and data type, filled entirely with a constant value.
# numpy.full(shape, fill_value, dtype=None)

np.full(10,7,dtype=int)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [55]:
np.full((2,2),8,dtype=int)

array([[8, 8],
       [8, 8]])

In [56]:
# The np.eye() function in NumPy creates a 2D array (matrix) with ones on the diagonal and zeros elsewhere. This is commonly known as an identity matrix when it is square

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
# The np.arange() function in NumPy creates a 1D array containing evenly spaced values within a specified numerical range. 
# numpy.arange(start,stop,step,dtype)

np.arange(1,10,2,dtype=int)

array([1, 3, 5, 7, 9])

In [61]:
# The np.linspace() function in NumPy creates a 1D array of evenly spaced numbers over a specified numerical interval.Unlike np.arange(), where you specify the step size, np.linspace() requires you to specify the exact number of elements you want. It automatically calculates the correct spacing, making it highly reliable for working with decimals and avoiding floating-point precision bugs

# numpy.linspace(start, stop, num=50, endpoint=True, dtype=None)
# endpoint: If True (default), stop is the last sample. If False, stop is excluded.

print(np.linspace(1,10,4,endpoint=True,dtype=int))
print(np.linspace(1,10,4,endpoint=False,dtype=int))

[ 1  4  7 10]
[1 3 5 7]
