# NumPy Cheat Sheet for Data Science

NumPy is one of the most important Python libraries for **Data Science, Machine Learning, and AI**. Focus especially on arrays, indexing, broadcasting, vectorization, aggregation, and linear algebra.

---

## 1. Import NumPy

```python
import numpy as np
```

Check version:

```python
np.__version__
```

---

# 2. Creating Arrays

### From Python lists

```python
a = np.array([1, 2, 3, 4])

b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
```

### Data types

```python
np.array([1, 2, 3], dtype=float)
np.array([1.2, 2.3], dtype=int)
```

---

## 3. Special Arrays

```python
np.zeros(5)
# [0. 0. 0. 0. 0.]

np.zeros((2, 3))

np.ones(5)
np.ones((2, 3))

np.full((2, 3), 7)

np.eye(3)       # Identity matrix
```

### Ranges

```python
np.arange(0, 10)
np.arange(0, 10, 2)

np.linspace(0, 1, 5)
```

Difference:

```python
np.arange(0, 10, 2)      # step-based
np.linspace(0, 10, 5)    # number-of-values based
```

---

# 4. Random Numbers

Very important for ML.

```python
np.random.rand(3, 2)

np.random.randn(3, 2)

np.random.randint(1, 10, size=(3, 3))
```

Set seed:

```python
np.random.seed(42)
```

Random choice:

```python
np.random.choice([1, 2, 3, 4], size=2)
```

---

# 5. Array Properties

```python
a.shape
a.ndim
a.size
a.dtype
```

Example:

```python
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

a.shape    # (2, 3)
a.ndim     # 2
a.size     # 6
a.dtype
```

### Important distinction

```text
shape → dimensions/size of each axis
ndim  → number of axes
size  → total number of elements
```

---

# 6. Reshaping

```python
a.reshape(2, 3)

a.reshape(3, 2)

a.reshape(-1)
```

`-1` means NumPy automatically calculates that dimension.

```python
a.reshape(-1, 1)
```

Very common for ML:

```python
X.reshape(-1, 1)
```

Convert to 1D:

```python
a.ravel()
a.flatten()
```

### `ravel()` vs `flatten()`

```text
ravel()   → usually returns a view
flatten() → returns a copy
```

---

# 7. Transpose

```python
a.T
```

or

```python
np.transpose(a)
```

Example:

```python
a.shape
# (2, 3)

a.T.shape
# (3, 2)
```

Very important in matrix operations.

---

# 8. Indexing

### 1D

```python
a = np.array([10, 20, 30, 40])

a[0]
a[-1]
a[1:3]
a[:3]
a[::2]
```

### 2D

```python
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

a[0, 1]     # 2
a[1, 2]     # 6
```

Entire row:

```python
a[0]
```

Entire column:

```python
a[:, 0]
```

Last column:

```python
a[:, -1]
```

---

# 9. Boolean Indexing

Extremely important for Data Science.

```python
a = np.array([10, 20, 30, 40, 50])

a[a > 25]
```

Output:

```python
[30 40 50]
```

Multiple conditions:

```python
a[(a > 20) & (a < 50)]
```

OR:

```python
a[(a < 20) | (a > 40)]
```

NOT:

```python
a[~(a > 20)]
```

⚠️ Use:

```python
&
|
~
```

instead of Python's:

```python
and
or
not
```

---

# 10. Fancy Indexing

```python
a = np.array([10, 20, 30, 40, 50])

a[[0, 2, 4]]
```

Output:

```python
[10 30 50]
```

2D:

```python
a[[0, 1], [1, 2]]
```

Gets:

```text
a[0,1]
a[1,2]
```

---

# 11. Mathematical Operations

NumPy performs **element-wise operations**.

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b
a - b
a * b
a / b
a ** 2
```

Important:

```python
a * b
```

means **element-wise multiplication**, NOT matrix multiplication.

---

# 12. Matrix Multiplication

Use:

```python
A @ B
```

or:

```python
np.matmul(A, B)
```

Example:

```python
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

A @ B
```

---

# 13. Broadcasting ⭐

One of the most important NumPy concepts for interviews.

```python
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([10, 20, 30])

a + b
```

NumPy effectively applies:

```text
[1,2,3] + [10,20,30]
[4,5,6] + [10,20,30]
```

Result:

```text
[[11,22,33],
 [14,25,36]]
```

### Broadcasting rule

Compare dimensions **from right to left**.

Two dimensions are compatible if:

```text
same size
OR
one of them is 1
```

Example:

```text
(2, 3)
(3,)
```

Treat `(3,)` as:

```text
(1, 3)
```

So:

```text
(2,3)
(1,3)
```

compatible.

But:

```text
(2,3)
(2,3,3)
```

❌ incompatible.

---

# 14. Aggregation Functions

Very common in Data Science.

```python
a.sum()
a.mean()
a.min()
a.max()
a.std()
a.var()
a.prod()
```

Also:

```python
np.sum(a)
np.mean(a)
np.median(a)
np.std(a)
np.var(a)
```

---

# 15. `axis` ⭐⭐⭐

This is **extremely important**.

Given:

```python
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
```

### `axis=0`

Operate **down the rows** → result for each column.

```python
a.sum(axis=0)
```

Result:

```text
[5, 7, 9]
```

### `axis=1`

Operate **across columns** → result for each row.

```python
a.sum(axis=1)
```

Result:

```text
[6, 15]
```

Think:

```text
axis=0 → collapse rows → column-wise result
axis=1 → collapse columns → row-wise result
```

---

# 16. Keep Dimensions

Useful in ML:

```python
a.mean(axis=0, keepdims=True)
```

Instead of:

```text
(3,)
```

you get:

```text
(1, 3)
```

This can prevent broadcasting problems.

---

# 17. Min/Max Index

```python
np.argmax(a)
np.argmin(a)
```

For a specific axis:

```python
np.argmax(a, axis=0)
np.argmax(a, axis=1)
```

Very useful for classification predictions:

```python
predicted_class = np.argmax(probabilities, axis=1)
```

---

# 18. Sorting

```python
np.sort(a)
```

Get sorting indices:

```python
np.argsort(a)
```

Example:

```python
a = np.array([30, 10, 20])

np.argsort(a)
```

Result:

```text
[1, 2, 0]
```

---

# 19. Unique Values

```python
np.unique(a)
```

With frequencies:

```python
values, counts = np.unique(
    a,
    return_counts=True
)
```

Very useful for categorical/class-label analysis.

---

# 20. Concatenation

```python
a = np.array([1, 2])
b = np.array([3, 4])

np.concatenate([a, b])
```

2D:

```python
np.concatenate([A, B], axis=0)
np.concatenate([A, B], axis=1)
```

---

# 21. Stack

### Vertical stack

```python
np.vstack([a, b])
```

### Horizontal stack

```python
np.hstack([a, b])
```

### Stack with new dimension

```python
np.stack([a, b], axis=0)
```

Important difference:

```text
concatenate → joins existing axis
stack       → creates a new axis
```

---

# 22. Split

```python
np.split(a, 2)
```

Horizontal:

```python
np.hsplit(a, 2)
```

Vertical:

```python
np.vsplit(a, 2)
```

---

# 23. Copy vs View ⭐

Important interview topic.

```python
b = a
```

Both point to the same array.

```python
b = a.copy()
```

Creates an independent copy.

Example:

```python
a = np.array([1, 2, 3])

b = a
b[0] = 100

print(a)
```

`a` also changes.

Use:

```python
b = a.copy()
```

when you need independence.

---

# 24. Handling Missing Values

NumPy uses `NaN`.

```python
a = np.array([1, 2, np.nan, 4])
```

Check:

```python
np.isnan(a)
```

Remove/filter:

```python
a[~np.isnan(a)]
```

Ignore NaN in calculations:

```python
np.nanmean(a)
np.nanmedian(a)
np.nansum(a)
np.nanstd(a)
```

---

# 25. Mathematical Functions

```python
np.abs(a)
np.sqrt(a)
np.square(a)
np.exp(a)
np.log(a)
np.log10(a)
np.log2(a)

np.sin(a)
np.cos(a)
np.tan(a)
```

---

# 26. Clipping

Limit values to a range:

```python
a = np.array([1, 5, 10, 20, 30])

np.clip(a, 5, 20)
```

Result:

```text
[5, 5, 10, 20, 20]
```

Useful for preprocessing and outlier handling.

---

# 27. Conditional Operations

```python
np.where(a > 10, 1, 0)
```

Example:

```python
scores = np.array([30, 70, 90])

np.where(scores >= 50, "Pass", "Fail")
```

---

# 28. Replace Values

```python
a[a < 0] = 0
```

Very common.

Example:

```python
X[X < 0] = 0
```

---

# 29. Linear Algebra ⭐⭐⭐

```python
np.linalg.inv(A)
np.linalg.det(A)
np.linalg.eig(A)
np.linalg.matrix_rank(A)
```

Norm:

```python
np.linalg.norm(A)
```

Solve equations:

```python
np.linalg.solve(A, b)
```

Dot product:

```python
np.dot(a, b)
```

Modern/common approach:

```python
a @ b
```

---

# 30. Random Sampling for ML

```python
X = np.random.randn(100, 5)
```

100 samples, 5 features.

Train/test-style random indices:

```python
indices = np.random.permutation(len(X))
```

Random sample:

```python
np.random.choice(
    len(X),
    size=20,
    replace=False
)
```

---

# 31. Normalization

### Min-Max Scaling

```python
X_min = X.min(axis=0)
X_max = X.max(axis=0)

X_scaled = (X - X_min) / (X_max - X_min)
```

Result range:

```text
0 → 1
```

### Standardization

```python
X_mean = X.mean(axis=0)
X_std = X.std(axis=0)

X_standardized = (X - X_mean) / X_std
```

Result approximately:

```text
mean = 0
std = 1
```

In real ML projects, you'd generally use `sklearn.preprocessing` rather than manually implementing this.

---

# 32. Dimensions in ML

Suppose:

```python
X.shape
```

returns:

```text
(1000, 20)
```

Meaning:

```text
1000 → samples
20   → features
```

Target:

```python
y.shape
```

could be:

```text
(1000,)
```

Sometimes you need:

```python
y.reshape(-1, 1)
```

which produces:

```text
(1000, 1)
```

This distinction is **very important for ML and broadcasting**.

---

# 33. Common Shape Conversions

```python
x.reshape(-1)
```

```text
(5,1) → (5,)
```

```python
x.reshape(-1, 1)
```

```text
(5,) → (5,1)
```

```python
x[:, np.newaxis]
```

same idea:

```text
(5,) → (5,1)
```

Add dimension:

```python
np.expand_dims(x, axis=0)
np.expand_dims(x, axis=1)
```

Remove dimension:

```python
np.squeeze(x)
```

---

# 34. Most Important Shape Patterns

Memorize these:

```text
(5,)       → 1D
(5, 1)     → 2D column vector
(1, 5)     → 2D row vector
(5, 3)     → 5 samples × 3 features
(32, 224, 224, 3) → batch of RGB images
```

---

# 35. NumPy Performance ⭐

Avoid Python loops when possible.

### Slow

```python
result = []

for x in data:
    result.append(x * 2)
```

### NumPy/vectorized

```python
result = data * 2
```

NumPy operations are generally much faster because they use optimized compiled implementations.

---

# 36. Useful Data Science Patterns

### Mean of every feature

```python
X.mean(axis=0)
```

### Standard deviation of every feature

```python
X.std(axis=0)
```

### Maximum value per feature

```python
X.max(axis=0)
```

### Minimum value per sample

```python
X.min(axis=1)
```

### Find rows containing NaN

```python
np.isnan(X).any(axis=1)
```

### Count NaNs

```python
np.isnan(X).sum()
```

### Count positive values

```python
(X > 0).sum()
```

### Find rows where all values are positive

```python
(X > 0).all(axis=1)
```

---

# 37. Essential Functions to Memorize

### Array creation

```python
np.array()
np.zeros()
np.ones()
np.full()
np.arange()
np.linspace()
```

### Shape

```python
.shape
.ndim
.size
.reshape()
.ravel()
.flatten()
.T
np.expand_dims()
np.squeeze()
```

### Selection

```python
[]
[:]
boolean indexing
np.where()
np.argmax()
np.argmin()
```

### Statistics

```python
np.mean()
np.median()
np.std()
np.var()
np.min()
np.max()
np.sum()
```

### Array manipulation

```python
np.concatenate()
np.stack()
np.vstack()
np.hstack()
np.split()
np.unique()
np.sort()
np.argsort()
```

### Math

```python
np.sqrt()
np.exp()
np.log()
np.abs()
np.clip()
```

### Linear algebra

```python
@
np.dot()
np.matmul()
np.linalg.inv()
np.linalg.det()
np.linalg.solve()
np.linalg.norm()
```

---

# 38. ⭐ What to Prioritize for Data Science Interviews

Don't try to memorize every NumPy function. Focus on these:

| Priority | Topic                              |
| -------- | ---------------------------------- |
| ⭐⭐⭐      | Array creation                     |
| ⭐⭐⭐      | `shape`, `ndim`, `size`            |
| ⭐⭐⭐      | Indexing & slicing                 |
| ⭐⭐⭐      | Boolean indexing                   |
| ⭐⭐⭐      | Broadcasting                       |
| ⭐⭐⭐      | `axis`                             |
| ⭐⭐⭐      | `reshape()`                        |
| ⭐⭐⭐      | Vectorization                      |
| ⭐⭐⭐      | `mean`, `std`, `sum`, `min`, `max` |
| ⭐⭐⭐      | `argmax`, `argsort`                |
| ⭐⭐       | `concatenate`, `stack`             |
| ⭐⭐       | `where()`                          |
| ⭐⭐       | NaN handling                       |
| ⭐⭐       | Copy vs view                       |
| ⭐⭐       | Linear algebra                     |
| ⭐        | Advanced NumPy internals           |

### The most important mental model

For Data Science, become extremely comfortable with:

```text
Array
 ↓
Shape
 ↓
Indexing
 ↓
Axis
 ↓
Broadcasting
 ↓
Vectorization
 ↓
Aggregation
 ↓
Reshaping
```

If you master those eight concepts, you'll understand **most of the NumPy you actually need for Data Science and ML interviews**.
